before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-filesystem-dev libboost-system-dev libboost-dev libgtest-dev libhtmlcxx-dev libcurl4-openssl-dev libjsoncpp-dev
  - git submodule update --init --recursive
script: "make"
