language: cpp
compiler:
  - clang
before_install:
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-filesystem1.48-dev libboost-system1.48-dev libboost1.48-dev libgtest-dev libhtmlcxx-dev libcurl4-openssl-dev libjsoncpp-dev
  #- sudo apt-get install g++-4.7
  #- export CXX="g++-4.7" CC="gcc-4.7"
  - sudo mkdir /usr/src/gtest/build
  - cd /usr/src/gtest/build
  - sudo cmake .. -DBUILD_SHARED_LIBS=1
  - sudo make -j4
  - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
  - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
  - cd -
  - git submodule update --init --recursive
script: make
