language: cpp
compiler:
  #- clang
  - gcc
before_install:
  #- sudo pip install cpp-coveralls --use-mirrors
  - sudo add-apt-repository ppa:fcitx-team/nightly -y
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository ppa:kxstudio-team/builds -y; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgflags-dev libboost-iostreams1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libboost-chrono1.48-dev libboost1.48-dev libgtest-dev libhtmlcxx-dev libcurl4-openssl-dev libjsoncpp-dev libleveldb-dev libsnappy-dev libprotobuf-dev protobuf-compiler
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq ggcov g++-4.8 --force-yes; export CXX="g++-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.2 --force-yes; fi
  - sudo mkdir /usr/src/gtest/build
  - cd /usr/src/gtest/build
  - sudo cmake .. -DBUILD_SHARED_LIBS=1
  - sudo make -j 4
  - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
  - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
  - cd -
  - git submodule update --init --recursive
script: make
#after_success: coveralls
